name: "Documentation macos test"
on:
- pull_request

jobs:
  sphinx:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip3 install -r doc/requirements.txt
        sudo apt install -y graphviz
        make docs
